from __future__ import annotations

from dataclasses import replace
from pathlib import Path
import subprocess
from typing import Any

from .types import ClusterProfile, LaunchJob


MASTER_PORT_EXPORT = """MASTER_PORT="$("${OPEN_WAM_ENV}/bin/python" - <<'PY'
import socket

with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
    sock.bind(("", 0))
    print(sock.getsockname()[1])
PY
)"
if [ -z "${MASTER_PORT}" ]; then
  echo "Failed to allocate MASTER_PORT" >&2
  exit 1
fi
export MASTER_PORT
"""


def write_sbatch(
    *,
    job: LaunchJob,
    cluster: ClusterProfile,
    repo_root: Path,
    sbatch_dir: Path,
    slurm_dir: Path,
    job_name_prefix: str,
    source_script: str,
    source_recipe: str,
) -> LaunchJob:
    sbatch_path = sbatch_dir / f"{job.index:02d}_{job.spec.name}.sbatch"
    script = render_sbatch(
        job=job,
        cluster=cluster,
        repo_root=repo_root,
        slurm_dir=slurm_dir,
        job_name_prefix=job_name_prefix,
        source_script=source_script,
        source_recipe=source_recipe,
    )
    sbatch_path.write_text(script, encoding="utf-8")
    sbatch_path.chmod(0o755)
    return replace(job, sbatch_path=sbatch_path)


def render_sbatch(
    *,
    job: LaunchJob,
    cluster: ClusterProfile,
    repo_root: Path,
    slurm_dir: Path,
    job_name_prefix: str,
    source_script: str,
    source_recipe: str,
) -> str:
    save_root = job.save_root
    wandb_dir = slurm_dir.parent / "wandb" / job.spec.name
    env_script = repo_root / cluster.env_script
    env_exports = "\n".join(f"export {key}={shell_quote(value)}" for key, value in job.env.items())
    command = " ".join(shell_quote(part) for part in job.command)
    return f"""#!/usr/bin/env bash
# Auto-generated by {source_script}.
# Source recipe: {source_recipe}
#SBATCH --job-name={job_name_prefix}-{job.spec.name}
#SBATCH --account={job.slurm['account']}
#SBATCH --partition={job.slurm['partition']}
#SBATCH --nodes=1
#SBATCH --gres=gpu:{job.slurm['gpus']}
#SBATCH --cpus-per-task={job.slurm['cpus_per_task']}
#SBATCH --mem={job.slurm['mem']}
#SBATCH --time={job.slurm['time']}
#SBATCH --no-requeue
#SBATCH --output={slurm_dir}/%x-%j.out
#SBATCH --error={slurm_dir}/%x-%j.err

set -euo pipefail

cd {repo_root}
source {shell_quote(str(env_script))}

export PYTHONUNBUFFERED=1
export TOKENIZERS_PARALLELISM="${{TOKENIZERS_PARALLELISM:-false}}"
export PYTORCH_CUDA_ALLOC_CONF="${{PYTORCH_CUDA_ALLOC_CONF:-expandable_segments:True}}"
{MASTER_PORT_EXPORT.rstrip()}
export WANDB_DIR={shell_quote(str(wandb_dir))}
{env_exports}

mkdir -p {shell_quote(str(save_root))}
mkdir -p "$WANDB_DIR"

{command}
"""


def run_sbatch_test_only(sbatch_path: Path, *, cwd: Path) -> dict[str, Any]:
    completed = subprocess.run(
        ["sbatch", "--test-only", str(sbatch_path)],
        cwd=str(cwd),
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        check=False,
    )
    return {
        "path": str(sbatch_path),
        "returncode": completed.returncode,
        "stdout": completed.stdout.strip(),
    }


def submit_sbatch(sbatch_path: Path, *, cwd: Path) -> str:
    completed = subprocess.run(
        ["sbatch", "--parsable", str(sbatch_path)],
        cwd=str(cwd),
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        check=True,
    )
    return completed.stdout.strip().splitlines()[-1]


def shell_quote(value: str | Path) -> str:
    raw = str(value)
    return "'" + raw.replace("'", "'\"'\"'") + "'"
